name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull akhaled797/kito-health-demo:latest
      
    - name: Delete Old docker container
      run: sudo docker rm -f kito-health-demo-container || true
      
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 NODE_ENV=prod --name kito-health-demo-container akhaled797/kito-health-demo
