name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker tag
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag akhaled797/kito-health-demo:${{ env.IMAGE_TAG }}

    - name: Push to Dockerhub
      run: docker push akhaled797/kito-health-demo:${{ env.IMAGE_TAG }}

    - name: Tag and push the image as 'latest'
      run: |
        docker tag akhaled797/kito-health-demo:${{ env.IMAGE_TAG }} akhaled797/kito-health-demo:latest
        docker push akhaled797/kito-health-demo:latest
